--TEST--
ibase_field_info(): basic fields
--SKIPIF--
<?php
include("skipif.inc");
?>
--FILE--
<?php

require_once('config.inc');
ini_set('ibase.default_charset', "NONE");

require("interbase.inc");
require("common.inc");

ibase_connect($test_base);
test_fields25();

?>
--EXPECT--
ID/INTEGER/4
SMALLINT_1/SMALLINT/2
INTEGER_FIELD/INTEGER/4
BIGINT_FIELD/BIGINT/8
NUMERIC_1/NUMERIC(4,4)/2
DECIMAL_1/NUMERIC(9,4)/4
NUMERIC_2/NUMERIC(9,8)/4
DECIMAL_2/NUMERIC(9,8)/4
NUMERIC_3/NUMERIC(18,16)/8
DECIMAL_3/NUMERIC(18,16)/8
FLOAT_FIELD/FLOAT/4
DOUBLE_FIELD/DOUBLE PRECISION/8
CHAR_FIXED/VARCHAR/10
VARCHAR_FIELD/VARCHAR/50
CHAR_UTF8/VARCHAR/40
VARCHAR_UTF8/VARCHAR/200
DATE_FIELD/DATE/4
TIME_FIELD/TIME/4
TIMESTAMP_FIELD/TIMESTAMP/8
BINARY_FIXED/VARCHAR/16
VARBINARY_FIELD/VARCHAR/100
BLOB_TEXT/BLOB/8
BLOB_BINARY/BLOB/8